baseURL = "/"
title = "Data for Good Israel"
theme = "meghna"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/animate-css/animate.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/wow/wow.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"

############################# Navigation ##################################
[[menu.main]]
name = "Events"
URL = "services"
weight = 2

[[menu.main]]
name = "Projects"
URL = "portfolio"
weight = 3

[[menu.main]]
name = "Team"
URL = "team"
weight = 4

############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Use the power of algorithm to solve social problems."
author = "Jeremy"
# Google Analitycs
googleAnalitycsID = "" # your id
# post share
post_share = true

# preloader
[params.preloader]
enable = true
preloader = "images/logo.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-calendar" # themify icon pack : https://themify.me/themify-icons
link = "https://www.meetup.com/Data-for-Good-Israel/"

[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/DataForGoodIL/"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/data-for-good-israel/"

[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/DataforGoodIsrael"

[[params.social]]
icon = "ti-email" # themify icon pack : https://themify.me/themify-icons
link = "mailto:info@dataforgoodisrael.com"



################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"

################################ Hebrew Language ########################
[Languages.he]
languageName = "He"
languageCode = "he"
contentDir = "content/hebrew"
weight = 2
home = "Home"
